-- 코드를 입력하세요
SELECT  YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        GENDER,
        COUNT(DISTINCT B.USER_ID) AS USERS
FROM  USER_INFO AS A
INNER JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID
WHERE GENDER IN(0,1)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC
