-- 코드를 입력하세요
SELECT B.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
JOIN CAR_RENTAL_COMPANY_CAR A ON B.CAR_ID = A.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = '10'
GROUP BY B.CAR_ID
ORDER BY B.CAR_ID DESC